#!/usr/bin/env ruby

require './lib/file_reader'
require 'optparse'

require 'optparse'
options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  opts.on("-f", "--file FILE", "File to process -f/--file test.txt") do |file|
    options[:file] = file
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

FileReader.new(options[:file]).run