#!/usr/bin/env ruby

require './lib/file_reader'
require 'optparse'

require 'optparse'
options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  opts.on("-f", "--file FILE", "File to process -f/--file test.txt") do |file|
    options[:file] = file
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

unless File.exist?(options[:file])
  puts "Please enter a file which exists"
  exit 1
end

unless File.extname(options[:file]) == ".txt"
  puts "Please only use a text file"
  exit 1
end

FileReader.new.run(options[:file])